version: 2.1

jobs:
  build0:
    docker:
      - image: cyversevice/jupyterlab-datascience:latest
    steps:
      - checkout
      - run: jupyter lab --version
  build1:
    docker:
      - image: cyversevice/jupyterlab-datascience:3.0.5
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/jupyterlab-datascience:2.2.9
    steps:
      - checkout
      - run: jupyter lab --version
  build3:
    docker:
      - image: cyversevice/jupyterlab-datascience:2.2.5
    steps:
      - checkout
      - run: jupyter lab --version
      
workflows:
  build:
    jobs:
      - build0
      - build1
      - build2
      - build3
