name: geospatial
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - altair
  - awscli
  - bottleneck
  - contextily
  - cython  
  - dask
  - h5py
  - humanize
  - gcsfs 
  - google-api-python-client
  - ipyleaflet 
  - ipyparallel
  - ipyvolume
  - ipywidgets
  - matplotlib
  - ncurses
  - netcdf4
  - nodejs
  - numcodecs 
  - oauth2client
  - opencv
  - palettable
  - pandas
  - pathlib2
  - pycrypto
  - pyhdf
  - pyresample
  - pyproj
  - pysal
  - rasterio
  - s3fs
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - six
  - spectral
  - statsmodels
  - tqdm
  - udunits2
  - wget 
# geospatial Conda Packages
  - entwine
  - geos
  - gdal
  - pdal
  - proj 
  - cartopy
  - fiona
  - folium
  - geopandas
  - earthengine-api
  - geemap 
  - planet
  - regionmask
  - satpy
  - xarray
  - xarray-topo
  - xarray-simlab
  - vega_datasets
  - zarr 